${{values.user}}-${{values.component_id}}
---
openapi: 3.0.3
info:
  title: quarkus-app API
  version: 1.0-SNAPSHOT
servers:
- url: https://${{values.user}}-${{values.component_id}}-dev-${{values.user}}-workshop-dev.{{values.cluster}}
  description: ${{values.user}}-${{values.component_id}} Dev
- url: https://${{values.user}}-${{values.component_id}}-preprod-${{values.user}}-workshop-preprod.{{values.cluster}}
  description: ${{values.user}}-${{values.component_id}} Preprod
- url: https://${{values.user}}-${{values.component_id}}-prod-${{values.user}}-workshop-prod.{{values.cluster}}
  description: ${{values.user}}-${{values.component_id}} Prod
paths:
  ${{values.api_endpoint}}:
    get:
      tags:
      - Example Resource
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
