---
apiVersion: v1
kind: Secret
metadata:
  name: ${{values.user}}-${{ values.component_id }}-repo
  namespace: ${{values.user}}-workshop
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: ${{ values.destination }}
